apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: j6crypto-gateway
    name: j6crypto-gateway
    namespace: j6crypto
  spec:
    type: LoadBalancer
    ports:
    - name: http
      port: 8081
      protocol: TCP
      targetPort: http
    selector:
      app: j6crypto-gateway
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: j6crypto-gateway
    namespace: j6crypto
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: j6crypto-gateway
    strategy:
      type: Recreate 
    template:
      metadata:
        labels:
          app: j6crypto-gateway
      spec:
        containers:    
        - env:
            - name: spring.cloud.zookeeper.discovery.instance-ip-address
              value: "127.0.0.2"
#              valueFrom:
#                fieldRef:
#                  fieldPath: status.podIP
            - name: spring.cloud.zookeeper.discovery.prefer-ip-address
              value: "true"
#            - name: spring.cloud.gateway.discovery.locator.enabled
#              value: "false"
#            - name: spring.cloud.zookeeper.discovery.enabled
#              value: "false"
            - name: spring.cloud.zookeeper.connect-string
              value: "zookeeper:2181"
            - name: spring.cloud.zookeeper.discovery.register
              value: "true"
            - name: spring.cloud.zookeeper.discovery.inetutils.preferred-networks
              value: "172.16"
            - name: server.port
              value: "8081"
            - name: spring.cloud.zookeeper.discovery.inetutils.ignoredInterfaces
              value: "eth0*"
          name: j6crypto-gateway
          ports:
          - containerPort: 8081
            name: http
          resources:
            requests:
              memory: 256Mi        
          image: jimmy6au/j6crypto-gateway:0.0.6-SNAPSHOT
          imagePullPolicy: Always    
kind: List
